language: java
jdk:
  - openjdk12  
  - openjdk11
  - openjdk10
  - openjdk9
  - openjdk8


addons:
  apt:
    packages:
      - ghostscript

env:
  - MAVEN_OPTS="-Dorg.slf4j.simpleLogger.defaultLogLevel=ERROR -Dorg.slf4j.simpleLogger.defaultLogLevel=warn"

install: mvn -q -B  install -Dgpg.skip
